apiVersion: v1
kind: PersistentVolume
metadata:
  name: java-app-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs_share
    server: knfs.dnixx.comm
